project:
  type: website
  output-dir: docs

website:
  page-navigation: false
  open-graph: true
  bread-crumbs: false
  title: Matching Methods
  description: Matching Method Estimation Strategies
  site-url: https://mcwayrm.github.io/matching_methods/
    
  page-footer: 
    right: "<div style='text-align:right;'>&copy; Copyright 2026, Ryan McWay. This site is built with <a href='https://quarto.org/' style='color:#1f4d4a;font-weight:bold;'>Quarto</a></div>"
    background: "#f2da61"

  sidebar:
    background: "#f2da61"
    pinned: true
    align: center
    style: "docked"
    collapse-level: 2
    search: true

    contents:
      - href: index.qmd
        text: Overview
      - href: concept.qmd
        text: The Concept
      - href: distance_measure.qmd
        text: Distance Measures
      - section: Matching Methods
        contents:
          - href: matching_psm.qmd
            text: Propensity Score Matching
          - href: matching_cvm.qmd
            text: Covariate Matching
          - href: matching_lasso.qmd
            text: LASSO Matching
          - href: matching_iptw.qmd
            text: Inverse Probability Weighting
          - href: matching_entropy.qmd
            text: Entropy Balancing
          - href: matching_double_robust.qmd
            text: Doubly Robust Estimation
      - href: sensitivity.qmd
        text: Sensitivity Analysis
      - section: Empirical Application
        contents:
          - href: practice.qmd
            text: Coding Practice
          - href: application_psp.qmd
            text: The PSP Program
      - href: resources.qmd
        text: Additional Resources

bibliography: references.bib

format:
  html:
    theme: [sandstone, theme.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
